In [72]:
import numpy as np
import pandas as pd

In [80]:
media = 4.95
desvio_padrao = 2
quantidade = 50

dados = np.random.normal(media,desvio_padrao,quantidade)

In [81]:
data = pd.DataFrame(dados) #valor de abertura

data

           0
0   3.042326
1   3.556875
2   7.300794
3   6.173816
4   6.367504
5   3.569123
6   4.466710
7   3.552829
8   1.638396
9   7.622347
10  3.284055
11  2.005762
12  5.867717
13  3.946920
14  4.914028
15  6.105475
16  1.293920
17  8.245623
18  4.234163
19  3.691950
20  5.601087
21  4.797230
22  2.278599
23  0.373298
24  6.095337
25  7.682439
26  6.396403
27  5.277725
28  6.132682
29  3.286253
30  5.338221
31  5.423398
32  7.913551
33  5.546019
34  6.908294
35  5.243670
36  6.076583
37  2.268973
38  3.828861
39  2.591187
40  6.547298
41  5.545529
42  1.587145
43  9.257042
44  4.826076
45  9.539329
46  4.542700
47  4.568914
48  3.535999
49  4.687861

In [85]:
mes = ['2° mes'] * 50

In [86]:
data.index = mes
data.index.name = 'Momento'

In [87]:
data.columns = ['Tempo de demora']

In [88]:
data

         Tempo de demora
Momento
2° mes          3.042326
2° mes          3.556875
2° mes          7.300794
2° mes          6.173816
2° mes          6.367504
2° mes          3.569123
2° mes          4.466710
2° mes          3.552829
2° mes          1.638396
2° mes          7.622347
2° mes          3.284055
2° mes          2.005762
2° mes          5.867717
2° mes          3.946920
2° mes          4.914028
2° mes          6.105475
2° mes          1.293920
2° mes          8.245623
2° mes          4.234163
2° mes          3.691950
2° mes          5.601087
2° mes          4.797230
2° mes          2.278599
2° mes          0.373298
2° mes          6.095337
2° mes          7.682439
2° mes          6.396403
2° mes          5.277725
2° mes          6.132682
2° mes          3.286253
2° mes          5.338221
2° mes          5.423398
2° mes          7.913551
2° mes          5.546019
2° mes          6.908294
2° mes          5.243670
2° mes          6.076583
2° mes          2.268973
2° mes          3.828861
2° mes          2.591187
2° mes          6.547298
2° mes          5.545529
2° mes          1.587145
2° mes          9.257042
2° mes          4.826076
2° mes          9.539329
2° mes          4.542700
2° mes          4.568914
2° mes          3.535999
2° mes          4.687861

In [89]:
data.to_csv("dados_teste2.csv")